### ISSUE TITLE
Add least norm solution 

### ISSUE THREAD

**Issue by wingos80** [wingos80/minesweeper_solved#11]
Least norm solution is a unique solution for an under determined linear system of equations. Would be interesting to see what the effect of seeding the LS solvers with this solution are.

**Comment by wingos80** [comment]
Or even try using the least norm solution as *the* solution.

**Comment by eliasboegel** [comment]
Reading up more on LSQR and LSMR, both of these yield the least-norm solution $min|x|$ to $|Ax-b|_2$:
https://stanford.edu/group/SOL/software/lsqr/
https://stanford.edu/group/SOL/software/lsmr/

**Comment by eliasboegel** [comment]
I think this can be closed given that now 3 solution methods yields the minimum norm solution.
